### ISSUE TITLE
Improve prediction of side to play

### ISSUE THREAD

**Issue by Elucidation** [Elucidation/tensorflow_chessbot#2]
Currently side to play prediction is default white, unless the words 'black' is in the title (some variations on that have been tested).

If a title doesn't have that, then white to play is default, but there are images where the board is flipped and it's black to play. Worse still, there are images where it's white to play and the board is flipped to be from black viewpoint, or vice versa.

Currently the responses show a FEN with what chessfenbot thinks is most likely to play, and then a reversed board position below in case it was wrong. This adds extra clutter/confusion to every comment, but not having it means several comments will not have the correct FEN.

Perhaps a simple check of location of black pieces vs white on which side, to determine board orientation, and side to play (with words in title overloading).

**Comment by gnarizzy** [comment]
Since the side to play is (almost always) the side that would have a winning computer evaluation, a crude but fairly effective heuristic would be to run a quick computer analysis for white to move and black to move, and select the side which has a higher evaluation as the side to move. You could pair this with words in the title as well to improve accuracy.

**Comment by Elucidation** [comment]
It's a bit much at this point to implement a chess engine analysis on the pieces, though there's some potential there with an easy python library to interface with like [Sunfish](https://github.com/thomasahle/sunfish). 

I could imagine people posting images where the side to play isn't the currently higher evaluation side, which is another thing I'd need to watch out for. 

I came across this solution with 9d442bd that seems to work reasonably well, basically counts up the number of black and white pieces on the top and bottom half of the board, and compares the two to decide which side the image is oriented by. This is only used as a fallback if the title doesn't contain any keywords.

**Comment by Elucidation** [comment]
Running implementation via  77c064f works for last 1000 posts
