### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by k2xl** [Elucidation/tensorflow_chessbot#25]
There's a memory leak in this library. If you loop getPrediction 100 times, you'll see the execution time gets slower and slower each time.

I narrowed it down to getTiles() function

**Comment by Elucidation** [comment]
I came across possibly the same leak when running for a long time, the default tensorflow graph kept growing every instantiation of predictor, implemented a reset here 5939ff5461f9e345530b6263d0d688df0656e2a5
