### ISSUE TITLE
inverted fen is not correct

### ISSUE THREAD

**Issue by Amleto** [Elucidation/tensorflow_chessbot#30]
https://www.reddit.com/r/chess/comments/76qmf6/black_to_play/

**Comment by Elucidation** [comment]
The word invert is used here to mean rotate/transpose, for cases where the bot incorrectly thought the board was oriented as white to play, the actual FENs look correct to me:

[Editor](https://www.lichess.org/editor/2r1k2r/pp4p1/2n2p1p/2RNn3/B2pP2B/5P2/bP2K1PP/R7_b_k)
> `2r1k2r/pp4p1/2n2p1p/2RNn3/B2pP2B/5P2/bP2K1PP/R7 b k -`

The rotated/transposed version of that would be:

[Editor](https://www.lichess.org/editor/7R/PP1K2Pb/2P5/B2Pp2B/3nNR2/p1p2n2/1p4pp/r2k1r2_b_-)
> `7R/PP1K2Pb/2P5/B2Pp2B/3nNR2/p1p2n2/1p4pp/r2k1r2 b - -`

I don't think there is a case where 'R7/...' is valid in the context of this image.

I may change the word 'invert' to 'rotate' to avoid this confusion in the future, feel free to re-open if I misunderstood something.

**Comment by Amleto** [comment]
The point of the FEN is to represent the board. The rook is at a1... the FEN should be R7 unless I'm missing something.

**Comment by Amleto** [comment]
ps, I don't know how to reopen this.

edit: found this: you cannot re-open your own issues if a repo collaborator closed them.
https://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github

**Comment by Amleto** [comment]
https://imgur.com/a/PnEFc

**Comment by ddugovic** [comment]
The strings look like [valid FEN](https://en.wikipedia.org/wiki/Forsyth–Edwards_Notation) and correct to me.

The starting position is `rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1` starting with the 8th rank and proceeding to the 1st rank.  So `R7...` would indicate a white rook on a8.

**Comment by Amleto** [comment]
"the contents of each square are described from file "a" through file "h"."

R7 is rook at a1.



On 18 Oct 2017 6:59 pm, "Daniel Dugovic" <notifications@github.com> wrote:

The strings look like valid FEN
<https://en.wikipedia.org/wiki/Forsyth%E2%80%93Edwards_Notation> and
correct to me.

The starting position is rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq
- 0 1 starting with the 8th rank and proceeding to the 1st rank. So R7...
would indicate a white rook on a8.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Elucidation/tensorflow_chessbot/issues/30#issuecomment-337676274>,
or mute the thread

**Comment by Elucidation** [comment]
@Amleto 

> R7 is rook at a1

Your own imgur editor link https://imgur.com/a/PnEFc shows the white rook on A1 as R7 at the end of the FEN, same as my bot's response.

I think we're agreeing that R7 is correct, but the R7 has to be at the end of the FEN string `.../R7`.

The inverted results are for when the bot misunderstands the rotation of the board (ie thinks the bottom left square is A1 when it's actually H8 or vice versa), which isn't the same as just changing sides, the FEN actually has to be inverted back to front to be made correct in those situations

**Comment by Amleto** [comment]
Yes, I think I only realised the 8 -> 1 rank thing when you linked the wiki, but I was still only thinking of the inverted fen instead of changing my attention to the initial fen.  My apologies!
