### ISSUE TITLE
Add a way to make requests outside of posting on reddit

### ISSUE THREAD

**Issue by Akababa** [Elucidation/tensorflow_chessbot#32]
I have an image I'd like to predict on but don't want to make a reddit post. Can the bot respond to private messages?

**Comment by Elucidation** [comment]
Not yet, but that is a good feature request

**Comment by Elucidation** [comment]
I had recently tried setting up a web-server which worked but cost ~$50/mo, so I dropped that for now.

I was able to port it to javascript using TensorflowJs so you can now run the bot through a web interface here: http://tetration.xyz/ChessboardFenTensorflowJs/
