### ISSUE TITLE
Decide on whether/how to reply to comments

### ISSUE THREAD

**Issue by Elucidation** [Elucidation/tensorflow_chessbot#8]
Brought to attention by one user replying to bot with an image expecting it to respond.

Could potentially check comments that call out to /u/ChessFenBot with images in them, and reply to the comment. 

This adds extra checks, potential to be abused, and not sure how many users actually want that.

**Comment by ddugovic** [comment]
ChessFenBot could also reply with the "probability" that a user-provided FEN would have been generated by the bot (or some measure of confidence in the bot's ability to have generated that FEN).
